// icon
export const icons = {
  production: {
    class: "fas fa-rocket",
    color: "yellow",
  },
  nebula: {
    class: "fab fa-gripfire",
    color: "rgb(194, 156, 255)",
  },
  shader: {
    class: "fas fa-dice-d20",
    color: "#00cce3",
  },
  template: {
    class: "fas fa-vector-square",
    color: "#aaaaaa",
  },
  troubleshoot: {
    class: "fas fa-industry",
    color: "#ff007d",
  },
  canvas2d: {
    class: "fas fa-vector-square",
    color: "#be7f08",
  },
  challenge: {
    class: "fas fa-cubes",
    color: "#10dd34",
  },
  copy: {
    class: "fas fa-copy",
    color: "#ff133f",
  },
}

// pages
export const list = [
  {
    title: "sphere",
    href: "24-08-19_fragment_09",
    thumb: "sphere.gif",
    icon: "production",
    fixed: true,
  },
  {
    title: "「球型」オブジェクトマルチマテリアル",
    href: "24-08-23_fragment_11_unit_sphere_spread",
    thumb: "sphere_spread.gif",
    icon: "none",
    fixed: true,
  },
  {
    title: "環境マップ",
    href: "24-10-05_envMap",
    thumb: "envMap.gif",
    icon: "none",
    fixed: true,
  },
  {
    title: "画像からパーティクル",
    href: "24-10-06_imgeToPoints",
    thumb: "imgToParticle.png",
    icon: "shader",
    fixed: true,
  },
  {
    title: `画像からパーティクル<br>（拡散）`,
    href: "24-10-08_imgeToPoints_spread",
    thumb: "imgToParticle_mesh.gif",
    icon: "shader",
    fixed: true,
  },
  {
    title: "画像からパーティクル<br />（拡散＋ノイズ）",
    href: "24-10-09_imgeToPoints_spread_noise",
    thumb: "imgToParticle_mesh_noise.gif",
    icon: "shader",
    fixed: true,
  },
  {
    title: "パーティクルごとに違う動きを取り入れる",
    href: "24-10-10_imgeToPoints_moves",
    thumb: "imgToParticle_moves.gif",
    icon: "shader",
    fixed: true,
  },
  {
    title: "パーティクルごとに色を塗る",
    href: "24-10-11_imgeToPoints_colors",
    thumb: "imgToParticle_colors.gif",
    icon: "shader",
    fixed: true,
  },
  {
    title: "GLTFLoader",
    href: "24-10-12_GLTFLoader",
    thumb: "GLTFLoader.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "GLTFLoader2",
    href: "24-10-12_GLTFLoader2",
    thumb: "GLTFLoader2.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "GLTFLoader3<br />blenderでテクスチャ編集",
    href: "24-10-12_GLTFLoader3",
    thumb: "GLTFLoader3.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "パスに沿って連続的に流れるパーティクル（参考）",
    href: "24-10-13_flowParticles",
    thumb: "flowParticles0.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "sphere_explosion（nebula）<br />をCDNで実現",
    href: "24-10-16_sphereExplosion_cdn",
    thumb: "sphere_explosion_CDN.gif",
    icon: "none",
    fixed: true,
  },
  {
    title: "sphere_explosion（nebula）<br />をテンプレで",
    href: "24-10-16_sphereExplosion_temp",
    thumb: "sphere_explosion_TEMP.gif",
    icon: "nebula",
    fixed: true,
  },
  {
    title: "パスに沿って連続的に流れるパーティクル",
    href: "24-10-17_flowParticles",
    thumb: "flowParticles2.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "GSAP 3D Animation 1",
    href: "24-10-19_GSAP3DAnimation1",
    thumb: "black.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "GSAP 3D Animation 2",
    href: "24-10-19_GSAP3DAnimation2",
    thumb: "GSAP3DAnimation2.gif",
    icon: "none",
    fixed: true,
  },
  {
    title: "GSAP 3D Animation path",
    href: "24-10-20_GSAP3DAnimation_path_mesh",
    thumb: "GSAP3DAnimationPath.gif",
    icon: "none",
    fixed: true,
  },
  {
    title: "GSAP 3D Animation path<br>（テンプレ）",
    href: "24-10-20_GSAP3DAnimation_path_mesh_template",
    thumb: "GSAP3DAnimation_path_mesh_template.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "GSAP3DAnimation path simple",
    href: "24-10-20_GSAP3DAnimation_path_simple",
    thumb: "GSAP3DAnimationPathSimple.gif",
    icon: "none",
    fixed: true,
  },
  {
    title: "importJsonCurve",
    href: "24-10-23_importJsonCurve",
    thumb: "importJsonCurve.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "flowSpace",
    href: "24-10-25_flowSpace",
    thumb: "flowSpace.png",
    icon: "production",
    fixed: true,
  },
  {
    title: "television",
    href: "24-10-12_GLTFLoader4_duck",
    thumb: "tv.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "sphere",
    href: "24-11-01_sphere",
    thumb: "black.png",
    icon: "production",
    fixed: true,
  },
  {
    title: "物理演算 cannon.js（1）<br>（基本）",
    href: "24-11-06_cannonJS_1",
    thumb: "CannonJS_1.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "物理演算 cannon.js（2）<br>（球、反発）",
    href: "24-11-06_cannonJS_2",
    thumb: "CannonJS_2.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "物理演算 ammo.js（1）<br>（基本）",
    href: "24-11-07_ammoJS_1",
    thumb: "ammoJS_1.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "物理演算 ammo.js（2）<br>（gltfにbodyを設定）",
    href: "24-11-07_ammoJS_2",
    thumb: "ammoJS_2.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "物理演算 ammo.js（3）<br>（当たり判定を正しく）",
    href: "24-11-07_ammoJS_3",
    thumb: "ammoJS_3.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "物理演算 ammo.js（4）<br>（sphere）",
    href: "24-11-07_ammoJS_4_sphere",
    thumb: "ammoJS_4_sphere.gif",
    icon: "none",
    fixed: true,
  },
  {
    title: "物理演算 ammo.js（5）<br>（body OK！）<br>⚫︎ マテリアルで分離",
    href: "24-11-08_ammoJS_5_sphere",
    thumb: "ammoJS_4_sphere.gif",
    icon: "none",
    fixed: false,
  },
  {
    title: "物理演算 ammo.js（6）<br>⚫︎ boxを下方で破棄",
    href: "24-11-09_ammoJS_6_sphere",
    thumb: "ammoJS_4_sphere.gif",
    icon: "none",
    fixed: false,
  },
  {
    title: "物理演算 ammo.js（7）<br>⚫︎ 出っ張りを動かす OK！",
    href: "24-11-10_ammoJS_7_sphere",
    thumb: "ammoJS_4_sphere.gif",
    icon: "none",
    fixed: false,
  },
  {
    title: "sphere",
    href: "24-11-11_ammoJS_8_sphere",
    thumb: "ammoJS_8_sphere.gif",
    icon: "production",
    fixed: false,
  },
  {
    title: "plateau",
    href: "24-11-12_plateau_ammoJS",
    thumb: "plateau_ammoJS.gif",
    icon: "production",
    fixed: false,
  },
  {
    title: "太い線",
    href: "24-11-13_lineGeometry",
    thumb: "lineGeometry.png",
    icon: "none",
    fixed: false,
  },
  {
    title: "かすれた線<br>（0.0 〜 1.0）",
    href: "24-11-13_blurredLine",
    thumb: "blurredLine.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "テンプレート Webgl<br>local OK",
    href: "24-11-13_template_webgl",
    thumb: "template.png",
    icon: "template",
    fixed: false,
  },
  {
    title: "線形補完 1",
    href: "24-11-14_linearCompletion_1",
    thumb: "linearCompletion_1.png",
    icon: "shader",
    fixed: false,
  },
  {
    title: "線形補完 2",
    href: "24-11-14_linearCompletion_2",
    thumb: "linearCompletion_2.png",
    icon: "shader",
    fixed: false,
  },
  {
    title: "線形補完 3<br>＊色の指定：CH12 BoxGeometry.html 参照",
    href: "24-11-14_linearCompletion_3",
    thumb: "linearCompletion_3.png",
    icon: "shader",
    fixed: false,
  },
  {
    title: "torus",
    href: "24-11-15_torus",
    thumb: "torus.png",
    icon: "production",
    fixed: false,
  },
  {
    title: "cube",
    href: "24-11-22_cube",
    thumb: "cube.png",
    icon: "none",
    fixed: true,
  },
  {
    title: "promise 演習",
    href: "24-11-16_promise",
    thumb: "black.gif",
    icon: "none",
    fixed: false,
  },
  {
    title: "nothingness",
    href: "24-11-17_nothingness",
    thumb: "nothingness.gif",
    icon: "production",
    fixed: false,
  },
  {
    title: "squares3 move",
    href: "http://btw2.html.xdomain.jp/pages/24-09-23_squares3_move",
    thumb: "squares3move.png",
    icon: "production",
    fixed: false,
  },
  {
    title: "parallelepiped<br>非同期Utilsの利用",
    href: "24-11-23_parallelepiped",
    thumb: "parallelepiped.png",
    icon: "none",
    fixed: false,
  },
  {
    title: "flow",
    href: "24-11-28_flow",
    thumb: "24-11-28_flow.png",
    icon: "production",
    fixed: false,
  },
  {
    title: "GLTFで影を表示",
    href: "24-12-07_gltf_shadow",
    thumb: "black.png",
    icon: "troubleshoot",
    fixed: false,
  },
  {
    title: "Dark Near Mouse 1（マウス位置の色を変える）",
    href: "24-12-12_darkNearMouse1",
    thumb: "24-12-12_darkNearMouse.png",
    icon: "shader",
    fixed: false,
  },
  {
    title: "Dark Near Mouse 2<br>（マウスの位置からの距離で色を変える）",
    href: "24-12-14_darkNearMouse2",
    thumb: "24-12-14_darkNearMouse2.png",
    icon: "shader",
    fixed: false,
  },
  {
    title: "Dark Near Mouse 1_3D<br>（マウス位置の色を変える ---> 3D）",
    href: "24-12-15_darkNearMouse3",
    thumb: "24-12-15_darkNearMouse3.png",
    icon: "shader",
    fixed: false,
  },
  {
    title: "Dark Near Mouse 2_3D<br>（マウスの位置からの距離で色を変える ---> 3D）",
    href: "24-12-15_darkNearMouse4",
    thumb: "24-12-15_darkNearMouse4.png",
    icon: "shader",
    fixed: false,
  },
  {
    title: "fragments<br> ＊ 新しいutils.js使用開始",
    href: "24-12-16_fragments",
    thumb: "24-12-16_fragments.png",
    icon: "none",
    fixed: false,
  },
  {
    title: "moveOnSpiral",
    href: "24-12-20_moveOnSpiral",
    thumb: "24-12-20_moveOnSpiral.png",
    icon: "none",
    fixed: false,
  },
  {
    title: "Canvas Fullscreen with Persistent Drawing<br>canvas2d に図形を描く",
    href: "24-12-26_canvas2d",
    thumb: "24-12-26_canvas2d.png",
    icon: "canvas2d",
    fixed: false,
  },
  {
    title: "fragments<br> ＊ 整理",
    href: "24-12-23_fragments2",
    thumb: "24-12-23_fragments2.png",
    icon: "none",
    fixed: false,
  },
  {
    title: "fragments",
    link: "http://btw.cloudfree.jp/pages/fragments",
    thumb: "24-12-28_fragments3.gif",
    icon: "production",
    fixed: true,
  },
  {
    title: "正式にモーフィング<br>（交わらない）",
    href: "25-01-15_morphCorrect",
    thumb: "25-01-15_morphCorrect.png",
    icon: "troubleshoot",
    fixed: false,
  },
  {
    title: "メッシュモーフィング<br>（交わらない）",
    href: "25-01-16_morphGrid",
    thumb: "25-01-16_morphGrid.png",
    icon: "none",
    fixed: false,
  },
  {
    title: "メッシュモーフィング 2<br>（交わらない）",
    href: "25-01-17_morphGrid2",
    icon: "none",
    fixed: false,
  },
  {
    title: "composition",
    href: "25-01-18_composition",
    icon: "none",
    fixed: false,
  },
  {
    title: "東北新社Top 再現 1<br>平面をつくる",
    links: "https://www.tfc.co.jp",
    href: "25-01-18_tfc1",
    icon: "none",
    fixed: false,
  },
  {
    title: "東北新社Top 再現 2<br>円がマウスに追従",
    links: "https://www.tfc.co.jp",
    href: "25-01-18_tfc2",
    icon: "none",
    fixed: false,
  },
  {
    title: "X 東北新社Top 再現 3<br>❶ main_tfc.jsの解読<br>❷ ページの再現<br>❸ シェーダーコードの理解",
    links: "https://www.tfc.co.jp",
    href: "25-01-18_tfc3",
    thumb: "25-01-18_tfc.gif",
    icon: "none",
    fixed: false,
  },
  {
    title: "メッシュモーフィング 3<br>マウスオンで徐々に",
    href: "25-01-18_morphGrid3",
    icon: "none",
    fixed: false,
  },
  {
    title: "practice39を<br>アレンジして再現",
    link: "https://liginc.co.jp/553484",
    href: "http://btw.html.xdomain.jp/three.js_book/practice/24-08-31_particle_morph3.html",
    thumb: "24-08-31_particle_morph3.png",
    icon: "none",
    fixed: false,
  },
  {
    title: "パーティクルのランダムな動き<br>（数学的に）",
    links: "https://liginc.co.jp/553484#,https://codepen.io/hisamikurita/pen/mdmPZxZ",
    href: "25-01-17_particle_random",
    icon: "challenge",
    fixed: false,
  },

  {
    title: "グラデーションをつくる 1<br>マウスポインタからの距離によって 青: 1.0 〜 0.0",
    href: "25-02-18_gradation",
    icon: "shader",
    fixed: true,
  },
  {
    title: "グラデーションをつくる 2<br>",
    href: "25-02-23_gradation",
    icon: "shader",
    fixed: true,
  },
  {
    title: "東北新社<br>（複製）",
    links: "https://www.tfc.co.jp",
    href: "25-02-04_TFC_prod",
    icon: "copy",
    fixed: false,
  },

  {
    title: "TFC 再現<br>エフェクト部分だけを再現",
    links: "https://www.tfc.co.jp",
    href: "25-02-17_TFC_done",
    icon: "challenge",
    fixed: false,
  },
  {
    title: "TFC 実装_1<br>379 shaderを動かす",
    href: "25-02-24_TFC_379",
    icon: "shader",
    fixed: false,
  },
]

// サムネ名はhrefと同じにする
// フォルダがない時は thumb: を書く
// iconが必要な時は書く
